from nltk.corpus import stopwords

stop_words = stopwords.words('english')

sentence = [('lab', 58), ('system', 53), ('report', 39), ('students', 36), ('lecturer', 26), ('course', 25),
            ('student', 23), ('reports', 19), ('use', 18), ('case', 18), ('repository', 16), ('lecturers', 16),
            ('description', 15), ('allows', 13), ('create', 13), ('portals', 13), ('interfaces', 12), ('user', 12),
            ('actors', 12), ('type', 12), ('srs', 11), ('document', 11), ('database', 11), ('primary', 11), ('essential', 11),
            ('documentation', 10), ('requirements', 10), ('deadline', 10), ('release', 9), ('latest', 9), ('submit', 9),
            ('view', 9), ('ta', 8), ('admin', 8), ('courses', 8), ('post', 8), ('portal', 8), ('administrator', 8),
            ('1.', 7), ('diagram', 7), ('results', 7), ('group', 7), ('join', 7), ('ieee', 6), ('2.', 6), ('lrrs', 6),
            ('submissions', 6), ('constraints', 5), ('new', 5), ('allow', 5), ('accounts', 5), ('using', 5), ('login', 5),
            ('his/her', 5), ('3.', 5), ('4.', 5), ('he/she', 5), ('specific', 5), ('public', 5), ('able', 5), ('purpose', 4),
            ('product', 4), ('setting', 4), ('submission', 4), ('design', 4), ('email', 4), ('work', 4), ('authorized', 4),
            ('id', 4), ('password', 4), ('groups', 4), ('accept', 4), ('joining', 4), ('visitors', 4), ('access', 4),
            ('std', 3), ('hardware', 3), ('site', 3), ('functions', 3), ('3.1.1', 3), ('management', 3), ('support', 3),
            ('users', 3), ('based', 3), ('result', 3), ('assignments', 3), ('php', 3), ('scripting', 3), ('language', 3),
            ('mysql', 3), ('posted', 3), ('operating', 3), ('registration', 3), ('creates', 3), ('5.', 3), ('acceptance', 3),
            ('without', 3), ('least', 3), ('communication', 3), ('disk', 3), ('required', 3), ('delete', 3), ('contents', 2),
            ('specifications', 2), ('introduction', 2), ('1.1', 2), ('1.2', 2), ('scope', 2), ('1.3', 2), ('definitions', 2),
            ('acronyms', 2), ('abbreviations', 2), ('overall', 2), ('perspective', 2), ('2.1.3', 2), ('2.1.4', 2),
            ('memory', 2), ('operations', 2), ('adaptation', 2), ('characteristics', 2), ('2.5', 2), ('assumptions', 2),
            ('dependencies', 2), ('2.6', 2), ('apportioning', 2), ('3.1', 2), ('uml', 2), ('descriptions', 2),
            ('details', 2), ('posting', 2), ('needed', 2), ('provides', 2), ('paperwork', 2), ('general', 2), ('used', 2),
            ('systems', 2), ('publish', 2), ('set', 2), ('sick', 2), ('way', 2), ('get', 2), ('server', 2), ('teaching', 2),
            ('assistant', 2), ('members', 2), ('registered', 2), ('institutes', 2), ('developed', 2), ('linux', 2),
            ('backend', 2), ('none', 2), ('register', 2), ('number', 2), ('consist', 2), ('step', 2), ('account', 2),
            ('administration', 2), ('one', 2), ('6.', 2), ('7.', 2), ('8.', 2), ('9.', 2), ('update', 2), ('10.', 2),
            ('11.', 2), ('12.', 2), ('notify', 2), ('visitor', 2), ('authentication', 2), ('environment', 2),
            ('important', 2), ('gb', 2), ('space', 2), ('hard', 2), ('may', 2), ('need', 2), ('make', 2), ('passport/id', 2),
            ('numbers', 2), ('process', 2), ('experience', 2), ('operation', 2), ('check', 2), ('data', 2), ('manage', 2),
            ('evaluate', 2), ('dec', 1), ('ii', 1),  ('mohamed', 1), ('elmahdi', 1), ('houzi', 1), ('12/27/2018', 1),
            ('file', 1), ('adapts', 1), ('guide', 1), ('830-1993', 1), ('table', 1), ('2.1', 1), ('2.1.1', 1), ('2.1.2', 1),
            ('2.1.5', 1), ('communications', 1), ('2.1.6', 1), ('2.1.7', 1), ('2.1.8', 1), ('2.2', 1), ('2.3', 1), ('2.4', 1),
            ('3.modeling', 1), ('4.references', 1), ('handle', 1), ('include', 1), ('marking', 1), ('automated', 1),
            ('version', 1), ('manual', 1), ('contains', 1), ('complete', 1), ('describes', 1), ('decisions', 1),
            ('architectural', 1), ('detailed', 1), ('implement', 1), ('visibility', 1), ('reliable', 1), ('fast', 1),
            ('great', 1), ('customers', 1), ('help', 1), ('daily', 1), ('routines', 1), ('deliver', 1), ('developing', 1),
            ('replace', 1), ('old', 1), ('increases', 1), ('efficiency', 1), ('reporting', 1), ('extend', 1),
            ('also', 1), ('convenient', 1), ('published', 1), ('benefit', 1), ('institution', 1), ('reduces', 1),
            ('headaches', 1), ('related', 1), ('publication', 1), ('centralized', 1), ('location', 1), ('miss', 1),
            ('assignment', 1), ('side', 1), ('specification', 1), ('relational', 1), ('institute', 1), ('electrical', 1),
            ('electronics', 1), ('engineers', 1), ('inc.', 1), ('deadlines', 1), ('various', 1), ('educational', 1),
            ('across', 1), ('globe', 1), ('simplifies', 1), ('2.1.', 1), ('proposed', 1), ('shall', 1), ('client/server', 1),
            ('architecture', 1), ('compatible', 1), ('microsoft', 1), ('windows', 1), ('2.1.1.', 1), ('2.1.2.', 1),
            ('following', 1), ('user-friendly', 1), ('menu', 1), ('driven', 1), ('entry', 1), ('valid', 1),
            ('passport', 1), ('two', 1), ('steps', 1), ('first', 1), ('identity', 1), ('checked', 1), ('lecturer/ta', 1),
            ('invites', 1), ('others', 1), ('could', 1), ('accept/reject', 1), ('invite', 1), ('enroll', 1),
            ('member', 1), ('disabled', 1), ('assign', 1), ('e.g', 1), ('individually', 1), ('done', 1), ('tas', 1),
            ('13.', 1), ('notification', 1), ('panel', 1), ('newly', 1), ('already', 1), ('joined', 1), ('14.', 1), ('see', 1),
            ('2.1.3.', 1), ('screen', 1), ('resolution', 1), ('computer', 1), ('mobile', 1), ('networked', 1), ('multi-', 1), ('2.1.4.', 1),
            ('ms-windows', 1), ('easyphp', 1), ('platform', 1), ('integrated', 1), ('development', 1), ('ide', 1), ('sublime', 1),
            ('2.1.5.', 1), ('different', 1), ('parts', 1), ('since', 1), ('depend', 1), ('however', 1), ('achieved', 1),
            ('therefore', 1), ('handled', 1), ('underlying', 1), ('2.1.6.', 1), ('ram', 1), ('run', 1), ('requirement', 1),
            ('increased', 1), ('provide', 1), ('alerts', 1), ('availability', 1), ('2.1.7.', 1), ('2.1.8.', 1), ('terminal', 1),
            ('client', 1), ('specified', 1), ('section', 1), ('respectively', 1), ('2.2.', 1), ('roles', 1), ('depending', 1),
            ('upon', 1), ('role', 1), ('modules', 1), ('authorization', 1), ('assigns', 1), ('flexible', 1), ('browse', 1),
            ('managed', 1), ('require', 1), ('posts', 1), ('inside', 1), ('view/download', 1), ('summary', 1), ('major', 1),
            ('perform', 1), ('facility', 1), ('enabling', 1), ('add', 1), ('modify', 1), ('2.3.', 1), ('qualification', 1),
            ('matriculation', 1), ('comfortable', 1), ('english', 1), ('well', 1), ('versed/informed', 1), ('technical', 1),
            ('elementary', 1), ('computers', 1), ('2.4.', 1), ('available', 1), ('reduce', 1), ('complexity', 1), ('hence', 1),
            ('careful', 1), ('deletion', 1), ('record', 1), ('responsible', 1), ('consistency', 1), ('must', 1), ('created', 1),
            ('communicated', 1), ('concerned', 1), ('confidentially', 1), ('avoid', 1), ('unauthorized', 1), ('assumed', 1),
            ('registering', 1), ('paid', 1), ('desired', 1), ('university', 1), ('fee', 1), ('modeling', 1), ('demonstrate', 1),
            ('objects', 1), ('interact', 1), ('map', 1), ('basic', 1), ('functionality', 1), ('main', 1), ('characters', 1), ('3.1.2', 1),
            ('initiated', 1), ('attempts', 1), ('action', 1), ('restricted', 1), ('prompted', 1), ('enter', 1), ('username', 1),
            ('order', 1), ('proceed', 1), ('secondary', 1), ('teacher', 1), ('according', 1), ('create/join', 1), ('schema', 1),
            ('blueprints', 1), ('represents', 1), ('structure', 1), ('types', 1), ('tables', 1), ('references', 1), ('engineering', 1),
            ('k.k', 1), ('aggarwal', 1), ('yogesh', 1), ('singh', 1), ('age', 1), ('publishing', 1), ('house', 1), ('2nd', 1), ('ed', 1),
            ('recommended', 1), ('practice', 1), ('830-1998', 1), ('standard', 1), ('test', 1), ('829-1998', 1)]


sentence = [(word, count) for word, count in sentence if word not in stop_words]

print (sentence)